import { FileTree } from 'nextra/components';

interface TitleProps {
  content?: string;
  name: string;
}

const Title = ({ content, name }: TitleProps) => {
  return (
    <div className="flex items-center justify-between w-[700px]">
      <div className="w-[150px]">{name}</div>
      {content && <div className="ml-[4px] w-[450px] text-[rgba(60,60,67,0.78)]">{`//${content}`}</div>}
    </div>
  );
};

const File = () => {
  return (
    <FileTree>
      <FileTree.Folder
        defaultOpen
        name="root"
      >
        <FileTree.Folder
          defaultOpen
          name={
            <Title
              content="vscode插件和设置"
              name=".vscode"
            />
          }
        >
          <FileTree.File
            name={
              <Title
                content="vscode推荐的插件"
                name="extensions.json"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="debug配置文件(debug React 和 TS)"
                name="launch.json"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="vscode配置(在该项目中生效，可以复制到用户配置文件中)"
                name="settings.json"
              />
            }
          />
        </FileTree.Folder>

        <FileTree.Folder
          defaultOpen
          name={
            <Title
              content="vite构建相关配置和插件"
              name="build"
            />
          }
        >
          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="构建打包配置"
                name="config"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="网络请求代理"
                  name="proxy.ts"
                />
              }
            />
          </FileTree.Folder>
          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="构建插件"
                name="plugins"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="插件汇总"
                  name="index.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="elegant-router插件"
                  name="router.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="unocss插件"
                  name="unocss.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="自动导入UI组件、自动解析iconify图标、自动解析本地svg作为图标"
                  name="unplugin.ts"
                />
              }
            />
          </FileTree.Folder>
        </FileTree.Folder>

        <FileTree.Folder
          defaultOpen
          name={
            <Title
              content="子项目"
              name="packages"
            />
          }
        >
          <FileTree.File
            name={
              <Title
                content="网络请求封装"
                name="axios"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="颜色调色板"
                name="color-palette"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="组合式函数hooks"
                name="hooks"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="组件物料"
                name="materials"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="网络请求封装"
                name="ofetch"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="脚本"
                name="scripts"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="工具函数"
                name="utils"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="uno-preset配置"
                name="uno-preset"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="工具函数"
                name="utils"
              />
            }
          />
        </FileTree.Folder>

        <FileTree.Folder
          defaultOpen
          name={
            <Title
              content="公共目录"
              name="public"
            />
          }
        >
          <FileTree.File
            name={
              <Title
                content="网站标签图标"
                name="favicon.svg"
              />
            }
          />
        </FileTree.Folder>

        <FileTree.Folder
          defaultOpen
          name={
            <Title
              content="源码目录"
              name="src"
            />
          }
        >
          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="静态资源"
                name="assets"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="图片"
                  name="imgs"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="本地svg图标"
                  name="svg-icon"
                />
              }
            />
          </FileTree.Folder>

          <FileTree.File
            name={
              <Title
                content="全局组件"
                name="components"
              />
            }
          />

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="常量"
                name="constants"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="app常量"
                  name="app.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="业务常量"
                  name="business.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="通用常量"
                  name="common.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="正则常量"
                  name="reg.ts"
                />
              }
            />
          </FileTree.Folder>

          <FileTree.File
            name={
              <Title
                content="hooks"
                name="hooks"
              />
            }
          />

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="功能模块"
                name="features"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="动画模块"
                  name="animate"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="ant design 相关的配置"
                  name="antdConfig"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="权限模块"
                  name="auth"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="表单模块"
                  name="form"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="语言模块"
                  name="lang"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="菜单模块"
                  name="menu"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="路由模块"
                  name="router"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="标签页模块"
                  name="tab"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="表格模块"
                  name="table"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="主题模块"
                  name="theme"
                />
              }
            />
          </FileTree.Folder>

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="布局组件"
                name="layouts"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="基础布局组件(包含全局头部、多页签、侧边栏、底部等公共部分)"
                  name="base-layout"
                />
              }
            />
            <FileTree.Folder
              name={
                <Title
                  content="布局组件模块"
                  name="modules"
                />
              }
            >
              <FileTree.File
                name={
                  <Title
                    content="全局头部"
                    name="global-header"
                  />
                }
              />
              <FileTree.File
                name={
                  <Title
                    content="全局菜单"
                    name="global-menu"
                  />
                }
              />
              <FileTree.File
                name={
                  <Title
                    content="全局搜索"
                    name="global-search"
                  />
                }
              />
              <FileTree.File
                name={
                  <Title
                    content="全局主体内容"
                    name="global-content"
                  />
                }
              />
              <FileTree.File
                name={
                  <Title
                    content="全局底部"
                    name="global-footer"
                  />
                }
              />
              <FileTree.File
                name={
                  <Title
                    content="全局Logo"
                    name="global-logo"
                  />
                }
              />
              <FileTree.File
                name={
                  <Title
                    content="全局侧边栏"
                    name="global-sider"
                  />
                }
              />

              <FileTree.File
                name={
                  <Title
                    content="布局的相关redux"
                    name="appStore"
                  />
                }
              />

              <FileTree.File
                name={
                  <Title
                    content="布局的hooks"
                    name="layoutHooks"
                  />
                }
              />
            </FileTree.Folder>
          </FileTree.Folder>

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="国际化配置"
                name="locales"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="语言文件"
                  name="langs"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="dayjs的国际化配置"
                  name="dayjs.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="语言文件汇总"
                  name="locale.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="Ant Design的国际化配置"
                  name="antd.ts"
                />
              }
            />
          </FileTree.Folder>

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="页面"
                name="pages"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="系统内置页面：异常页等"
                  name="_builtin"
                />
              }
            />
          </FileTree.Folder>
        </FileTree.Folder>
      </FileTree.Folder>
    </FileTree>
  );
};

export default File;
