import { FileTree } from 'nextra/components';

interface TitleProps {
  content?: string;
  name: string;
}

const Title = ({ content, name }: TitleProps) => {
  return (
    <div className="flex items-center justify-between w-[700px]">
      <div className="w-[150px]">{name}</div>
      {content && <div className="ml-[4px] w-[450px] text-[rgba(60,60,67,0.78)]">{`//${content}`}</div>}
    </div>
  );
};

const File = () => {
  return (
    <FileTree>
      <FileTree.Folder
        defaultOpen
        name="root"
      >
        <FileTree.Folder
          defaultOpen
          name={
            <Title
              content="vscode插件和设置"
              name=".vscode"
            />
          }
        >
          <FileTree.File
            name={
              <Title
                content="vscode推荐的插件"
                name="extensions.json"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="debug配置文件(debug React 和 TS)"
                name="launch.json"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="vscode配置(在该项目中生效，可以复制到用户配置文件中)"
                name="settings.json"
              />
            }
          />
        </FileTree.Folder>

        <FileTree.Folder
          defaultOpen
          name={
            <Title
              content="vite构建相关配置和插件"
              name="build"
            />
          }
        >
          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="构建打包配置"
                name="config"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="网络请求代理"
                  name="proxy.ts"
                />
              }
            />
          </FileTree.Folder>
          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="构建插件"
                name="plugins"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="插件汇总"
                  name="index.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="elegant-router插件"
                  name="router.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="unocss插件"
                  name="unocss.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="自动导入UI组件、自动解析iconify图标、自动解析本地svg作为图标"
                  name="unplugin.ts"
                />
              }
            />
          </FileTree.Folder>
        </FileTree.Folder>

        <FileTree.Folder
          defaultOpen
          name={
            <Title
              content="子项目"
              name="packages"
            />
          }
        >
          <FileTree.File
            name={
              <Title
                content="网络请求封装"
                name="axios"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="颜色调色板"
                name="color-palette"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="组合式函数hooks"
                name="hooks"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="组件物料"
                name="materials"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="网络请求封装"
                name="ofetch"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="脚本"
                name="scripts"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="工具函数"
                name="utils"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="uno-preset配置"
                name="uno-preset"
              />
            }
          />
          <FileTree.File
            name={
              <Title
                content="工具函数"
                name="utils"
              />
            }
          />
        </FileTree.Folder>

        <FileTree.Folder
          defaultOpen
          name={
            <Title
              content="公共目录"
              name="public"
            />
          }
        >
          <FileTree.File
            name={
              <Title
                content="网站标签图标"
                name="favicon.svg"
              />
            }
          />
        </FileTree.Folder>

        <FileTree.Folder
          defaultOpen
          name={
            <Title
              content="源码目录"
              name="src"
            />
          }
        >
          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="静态资源"
                name="assets"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="图片"
                  name="imgs"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="本地svg图标"
                  name="svg-icon"
                />
              }
            />
          </FileTree.Folder>

          <FileTree.File
            name={
              <Title
                content="全局组件"
                name="components"
              />
            }
          />

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="常量"
                name="constants"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="app常量"
                  name="app.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="业务常量"
                  name="business.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="通用常量"
                  name="common.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="正则常量"
                  name="reg.ts"
                />
              }
            />
          </FileTree.Folder>

          <FileTree.File
            name={
              <Title
                content="hooks"
                name="hooks"
              />
            }
          />

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="功能模块"
                name="features"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="动画模块"
                  name="animate"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="ant design 相关的配置"
                  name="antdConfig"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="权限模块"
                  name="auth"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="表单模块"
                  name="form"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="语言模块"
                  name="lang"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="菜单模块"
                  name="menu"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="路由模块"
                  name="router"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="标签页模块"
                  name="tab"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="表格模块"
                  name="table"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="主题模块"
                  name="theme"
                />
              }
            />
          </FileTree.Folder>

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="布局组件"
                name="layouts"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="基础布局组件(包含全局头部、多页签、侧边栏、底部等公共部分)"
                  name="base-layout"
                />
              }
            />
            <FileTree.Folder
              name={
                <Title
                  content="布局组件模块"
                  name="modules"
                />
              }
            >
              <FileTree.File
                name={
                  <Title
                    content="全局头部"
                    name="global-header"
                  />
                }
              />
              <FileTree.File
                name={
                  <Title
                    content="全局菜单"
                    name="global-menu"
                  />
                }
              />
              <FileTree.File
                name={
                  <Title
                    content="全局搜索"
                    name="global-search"
                  />
                }
              />
              <FileTree.File
                name={
                  <Title
                    content="全局主体内容"
                    name="global-content"
                  />
                }
              />
              <FileTree.File
                name={
                  <Title
                    content="全局底部"
                    name="global-footer"
                  />
                }
              />
              <FileTree.File
                name={
                  <Title
                    content="全局Logo"
                    name="global-logo"
                  />
                }
              />
              <FileTree.File
                name={
                  <Title
                    content="全局侧边栏"
                    name="global-sider"
                  />
                }
              />

              <FileTree.File
                name={
                  <Title
                    content="布局的相关redux"
                    name="appStore"
                  />
                }
              />

              <FileTree.File
                name={
                  <Title
                    content="布局的hooks"
                    name="layoutHooks"
                  />
                }
              />
            </FileTree.Folder>
          </FileTree.Folder>

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="国际化配置"
                name="locales"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="语言文件"
                  name="langs"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="dayjs的国际化配置"
                  name="dayjs.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="语言文件汇总"
                  name="locale.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="Ant Design的国际化配置"
                  name="antd.ts"
                />
              }
            />
          </FileTree.Folder>

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="页面"
                name="pages"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="系统内置页面：异常页等"
                  name="_builtin"
                />
              }
            />

            <FileTree.File
              name={
                <Title
                  content="基本布局"
                  name="(base)"
                />
              }
            />

            <FileTree.File
              name={
                <Title
                  content="空白布局"
                  name="(blank)"
                />
              }
            />

            <FileTree.File
              name={
                <Title
                  content="全局错误页"
                  name="error.tsx"
                />
              }
            />

            <FileTree.File
              name={
                <Title
                  content="根路由"
                  name="index.tsx"
                />
              }
            />

            <FileTree.File
              name={
                <Title
                  content="全局布局组件 主要用来进行路由鉴权"
                  name="layout.tsx"
                />
              }
            />

            <FileTree.File
              name={
                <Title
                  content="全局错误页"
                  name="error.tsx"
                />
              }
            />

            <FileTree.File
              name={
                <Title
                  content="全局loading"
                  name="loading.tsx"
                />
              }
            />
          </FileTree.Folder>

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="插件"
                name="plugins"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="各种依赖的静态资源导入(css、scss等)"
                  name="assets.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="dayjs插件"
                  name="dayjs.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="iconify插件"
                  name="iconify.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="顶部加载条nprogress插件"
                  name="nprogress.ts"
                />
              }
            />
          </FileTree.Folder>

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="react路由"
                name="router"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="elegant-router插件生成的路由声明、导入和转换等文件"
                  name="elegant"
                />
              }
            />

            <FileTree.Folder
              name={
                <Title
                  content="路由声明入口"
                  name="routes"
                />
              }
            >
              <FileTree.File
                name={
                  <Title
                    content="系统内置路由 自定义路由"
                    name="builtin"
                  />
                }
              />
              <FileTree.File
                name={
                  <Title
                    content="前端静态路由创建的入口"
                    name="index"
                  />
                }
              />
            </FileTree.Folder>
            <FileTree.File
              name={
                <Title
                  content="路由插件入口"
                  name="index.ts"
                />
              }
            />
          </FileTree.Folder>

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="网络请求"
                name="service"
              />
            }
          >
            <FileTree.Folder
              defaultOpen
              name={
                <Title
                  content="接口api"
                  name="api"
                />
              }
            >
              <FileTree.File
                name={
                  <Title
                    content="封装的请求函数"
                    name="request"
                  />
                }
              />
            </FileTree.Folder>
          </FileTree.Folder>

          <FileTree.File
            name={
              <Title
                content="redux状态管理"
                name="store"
              />
            }
          />

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="全局样式"
                name="styles"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="css"
                  name="css"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="scss"
                  name="scss"
                />
              }
            />
          </FileTree.Folder>

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="主题配置"
                name="theme"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="主题默认配置及覆盖配置"
                  name="settings.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="主题token对应的css变量"
                  name="vars.ts"
                />
              }
            />
          </FileTree.Folder>

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="TS类型声明文件(*.d.ts)"
                name="types"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="请求接口返回的数据的类型声明"
                  name="api.d.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="应用相关的类型声明"
                  name="app.d.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="通用类型声明"
                  name="common.d.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="自动导入的组件的类型声明"
                  name="components.d.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="插件elegant-router生成的路由声明"
                  name="elegant-router.d.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="react路由描述和请求环境相关的类型声明"
                  name="env.d.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="Ant Design类型"
                  name="antd.d.ts"
                />
              }
            />

            <FileTree.File
              name={
                <Title
                  content="路由描述的类型声明"
                  name="router.d.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="本地缓存的数据类型"
                  name="storage.d.ts"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="联合类型"
                  name="union-key.d.ts"
                />
              }
            />
          </FileTree.Folder>

          <FileTree.Folder
            defaultOpen
            name={
              <Title
                content="全局工具函数(纯函数，不含状态)"
                name="utils"
              />
            }
          >
            <FileTree.File
              name={
                <Title
                  content="通用工具函数"
                  name="common"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="图标相关工具函数"
                  name="icon"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="请求服务配置相关的工具函数"
                  name="service"
                />
              }
            />
            <FileTree.File
              name={
                <Title
                  content="存储相关工具函数"
                  name="storage"
                />
              }
            />
          </FileTree.Folder>

          <FileTree.File
            name={
              <Title
                content="React文件入口"
                name="App.tsx"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="项目入口TS文件"
                name="main.tsx"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="统一编辑器配置"
                name=".editorconfig"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="环境文件"
                name=".env"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="生产环境的环境文件"
                name=".env.prod"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="测试环境的环境文件"
                name=".env.test"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="git属性配置"
                name=".gitattributes"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="忽略git提交的配置文件"
                name=".gitignore"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="npm配置 "
                name=".npmrc"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="项目更新日志"
                name="CHANGELOG.md"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="eslint flat配置文件"
                name="eslint.config.js"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="html文件"
                name="index.html"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="npm依赖描述文件"
                name="package.json"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="npm包管理器pnpm依赖锁定文件"
                name="pnpm-lock.yaml"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="项目介绍文档"
                name="README.md"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="项目介绍文档(中文)"
                name="README.zh-CN.md"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="TS配置"
                name="tsconfig.json"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="原子css框架unocss配置"
                name="uno.config.ts"
              />
            }
          />

          <FileTree.File
            name={
              <Title
                content="vite配置"
                name="vite.config.ts"
              />
            }
          />
        </FileTree.Folder>
      </FileTree.Folder>
    </FileTree>
  );
};

export default File;
